### ISSUE TITLE
Windows: nijz_daily.py fails on Windows

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/data#107]
@AuroraBode is using Windows to run nijz_daily. Script fails with error on ajdovščina so the suspect is encoding issue.

```
INFO:C:\Users\Delo\Documents\GitHub\data\transform\nijz_daily.py:SOURCE_FILE: C:\Users\Delo\Documents\COVID-DATA\EPI\dnevni_prikazi20210225.xlsx
Traceback (most recent call last):
  File "C:\Users\Delo\Documents\GitHub\data\transform\nijz_daily.py", line 62, in <module>
    df = df.rename(mapper=get_municipality_header, axis='columns')  # transform of municipality names
  File "C:\Users\Delo\Documents\GitHub\data\venv\lib\site-packages\pandas\util\_decorators.py", line 309, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Delo\Documents\GitHub\data\venv\lib\site-packages\pandas\core\frame.py", line 4300, in rename
    return super().rename(
  File "C:\Users\Delo\Documents\GitHub\data\venv\lib\site-packages\pandas\core\generic.py", line 947, in rename
    new_index = ax._transform_index(f, level)
  File "C:\Users\Delo\Documents\GitHub\data\venv\lib\site-packages\pandas\core\indexes\base.py", line 4836, in _transform_index
    items = [func(x) for x in self]
  File "C:\Users\Delo\Documents\GitHub\data\venv\lib\site-packages\pandas\core\indexes\base.py", line 4836, in <listcomp>
    items = [func(x) for x in self]
  File "C:\Users\Delo\Documents\GitHub\data\transform\nijz_daily.py", line 52, in get_municipality_header
    region = municipalities[m]['region']
KeyError: 'ajdovščina'
```

**Comment by mojca** [comment]
I cannot reproduce the problem. It works for me just fine under both powershell and mingw64 with Python 3.8.

@AuroraBode: can we get more information? How did you install Python and which version do you use? Did you perhaps test this with Python 2.7? Unicode support underwent major changes between Python 2 and 3.

**Comment by lukarenko** [comment]
Will reopen if reproduced/needed again
